<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-AAJ02US" name="tests.lesson1.pageObject.SendEmailTest" tests="4" failures="1" timestamp="26 Feb 2021 08:42:54 GMT" time="122.412" errors="0">
  <testcase name="checkingLoginToTheEmailAndSendingTheMail" time="8.775" classname="tests.lesson1.pageObject.SendEmailTest"/>
  <testcase name="checkDownloading" time="33.300" classname="tests.lesson1.pageObject.SendEmailTest">
    <failure type="java.lang.AssertionError" message="File was not downloaded expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: File was not downloaded expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at pages.lesson1.PageObject.BasePage.assertTrue(BasePage.java:86)
at pages.lesson1.PageObject.UkrNetHomePage.checkFileDownloading(UkrNetHomePage.java:115)
at tests.lesson1.pageObject.SendEmailTest.checkDownloading(SendEmailTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- checkDownloading -->
  <testcase name="checkDownloading" time="69.387" classname="tests.lesson1.pageObject.SendEmailTest"/>
  <testcase name="checkingLoginToTheEmailAndSendingTheMail" time="10.950" classname="tests.lesson1.pageObject.SendEmailTest"/>
</testsuite> <!-- tests.lesson1.pageObject.SendEmailTest -->
